name: 'WorkflowHub Submission'
description: 'Submit a workflow to WorkflowHub'
inputs:
  team_id:
    description: 'ID of the WorkflowHub Team to own the submitted workflows'
    required: true
  instance:
    description: 'URL of the WorkflowHub instance to submit to'
    required: false
    default: 'https://workflowhub.eu'
outputs:
  workflow_urls: # id of output
    description: 'URLs of the WorkflowHub entries registered'
    value: ${{ steps.workflowhub-submission.outputs.workflow_urls }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.team_id }}
    - ${{ inputs.instance }}
